#!/usr/bin/env bash
# Install Grok Build Usage as a macOS menu-bar app (+ optional login item).
#
# Usage:
#   ./scripts/install-app.sh              # build ~/Applications/Grok Build Usage.app
#   ./scripts/install-app.sh --login      # also start at login (LaunchAgent)
#   ./scripts/install-app.sh --open       # launch after install
#   ./scripts/install-app.sh --login --open
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
APP_NAME="Grok Build Usage"
APP_DIR="${HOME}/Applications/${APP_NAME}.app"
# Neutral reverse-DNS id (not personal) — used for LaunchAgent + Info.plist
BUNDLE_ID="app.grokbuild.usage"
LAUNCH_AGENT_DIR="${HOME}/Library/LaunchAgents"
LAUNCH_AGENT_PLIST="${LAUNCH_AGENT_DIR}/${BUNDLE_ID}.plist"
LOG_DIR="${HOME}/Library/Logs"
LOG_FILE="${LOG_DIR}/grok-build-usage.log"

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "error: Grok Build Usage is macOS-only." >&2
  exit 1
fi

if [[ ! -f "${HOME}/.grok/auth.json" ]]; then
  echo "note: ~/.grok/auth.json not found yet."
  echo "      Install/open Grok Build and run:  grok login"
  echo "      (or /login inside the TUI). You can still install the app now."
  echo ""
fi

DO_LOGIN=0
DO_OPEN=0
for arg in "$@"; do
  case "$arg" in
    --login) DO_LOGIN=1 ;;
    --open)  DO_OPEN=1 ;;
    -h|--help)
      sed -n '2,12p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown flag: $arg" >&2
      exit 2
      ;;
  esac
done

echo "==> Project:  ${PROJECT_DIR}"
echo "==> App:      ${APP_DIR}"

# ── Ensure venv + package ───────────────────────────────────────────────────
if [[ ! -x "${PROJECT_DIR}/.venv/bin/python" ]]; then
  echo "==> Creating venv (python3.11 preferred)…"
  if command -v python3.11 >/dev/null 2>&1; then
    python3.11 -m venv "${PROJECT_DIR}/.venv"
  else
    python3 -m venv "${PROJECT_DIR}/.venv"
  fi
fi

# shellcheck disable=SC1091
source "${PROJECT_DIR}/.venv/bin/activate"
python -m pip install -q -U pip setuptools wheel
python -m pip install -q -e "${PROJECT_DIR}"
deactivate

PYTHON_BIN="${PROJECT_DIR}/.venv/bin/python"
if ! "${PYTHON_BIN}" -c "import gbu" 2>/dev/null; then
  echo "error: gbu package not importable from ${PYTHON_BIN}" >&2
  exit 1
fi

# Resolve real interpreter + stdlib home so we can embed a *named* Mach-O inside
# the .app. System Settings → Desktop & Dock → "Allow in the Menu Bar" labels
# entries by the running executable; exec'ing bare python3.11 shows "python3.11".
# A copy of the interpreter living at Contents/MacOS/GrokBuildUsage is attributed
# to this bundle and shows as "Grok Build Usage".
PY_META="$("${PYTHON_BIN}" - <<'PY'
import pathlib, sys
print(f"{sys.version_info.major}.{sys.version_info.minor}")
print(pathlib.Path(sys.executable).resolve())
print(sys.base_prefix)
PY
)"
PY_VERSION="$(printf '%s\n' "${PY_META}" | sed -n '1p')"
REAL_PYTHON="$(printf '%s\n' "${PY_META}" | sed -n '2p')"
PYTHON_HOME="$(printf '%s\n' "${PY_META}" | sed -n '3p')"
SITE_PACKAGES="${PROJECT_DIR}/.venv/lib/python${PY_VERSION}/site-packages"
SRC_PATH="${PROJECT_DIR}/src"
echo "==> Python ${PY_VERSION}  home=${PYTHON_HOME}"
echo "    real binary: ${REAL_PYTHON}"
if [[ ! -x "${REAL_PYTHON}" ]]; then
  echo "error: could not resolve real Python binary from venv" >&2
  exit 1
fi
if [[ ! -d "${PYTHON_HOME}" ]]; then
  echo "error: PYTHON home missing at ${PYTHON_HOME}" >&2
  exit 1
fi
if [[ ! -d "${SITE_PACKAGES}" ]]; then
  echo "error: site-packages missing at ${SITE_PACKAGES}" >&2
  exit 1
fi

# ── Build .app bundle ───────────────────────────────────────────────────────
echo "==> Building app bundle…"
rm -rf "${APP_DIR}"
mkdir -p "${APP_DIR}/Contents/MacOS" "${APP_DIR}/Contents/Resources"

# Embed a copy of the interpreter under a bundle-local name (not a symlink —
# macOS resolves symlink targets). Keep the *original* linker-signed CDHash:
# System Settings → Menu Bar → "Allow in the Menu Bar" already has a sticky
# row named "python3.11" for that code identity. Ad-hoc re-signing breaks the
# match (new CDHash) and the new identity never gets its own Settings row, so
# the status item stays permanently height-0. Correct long-term naming needs a
# non-Python host binary + a clean Control Center registration — not re-sign.
echo "==> Embedding interpreter as Contents/MacOS/GrokBuildUsage…"
cp "${REAL_PYTHON}" "${APP_DIR}/Contents/MacOS/GrokBuildUsage"
chmod +x "${APP_DIR}/Contents/MacOS/GrokBuildUsage"

# Launcher — Launch Services entry point; execs the in-bundle runtime.
# Logs to ~/Library/Logs. Sets PYTHONHOME/PYTHONPATH so the relocated binary
# finds the stdlib + this project's venv packages.
cat > "${APP_DIR}/Contents/MacOS/gbu" <<EOF
#!/usr/bin/env bash
# Grok Build Usage — menu bar launcher (generated by install-app.sh)
#
# Launch paths matter on recent macOS:
#   - LaunchAgent / direct exec → status item gets a real menu-bar frame
#   - Finder / \`open\` / Spotlight (Launch Services) → often height-0 forever
#     (Control Center allow-list identity differs)
# So when this script is NOT already running as our LaunchAgent job, re-dispatch
# via launchctl kickstart instead of exec'ing Python under Launch Services.
set -euo pipefail

DIR="\$(cd "\$(dirname "\$0")" && pwd)"
PROJECT_DIR="${PROJECT_DIR}"
RUNTIME="\${DIR}/GrokBuildUsage"
PYTHON_HOME="${PYTHON_HOME}"
PYTHONPATH="${SRC_PATH}:${SITE_PACKAGES}"
LOG_DIR="${LOG_DIR}"
LOG_FILE="${LOG_FILE}"
BUNDLE_ID="${BUNDLE_ID}"
DOMAIN="gui/\$(id -u)"
mkdir -p "\${LOG_DIR}"

if [[ ! -x "\${RUNTIME}" ]]; then
  osascript -e 'display notification "GrokBuildUsage runtime missing — re-run install-app.sh" with title "Grok Build Usage"' 2>/dev/null || true
  echo "missing runtime: \${RUNTIME}" >>"\${LOG_FILE}"
  exit 1
fi

# Real process start: LaunchAgent sets XPC_SERVICE_NAME to our label.
# GBU_DIRECT=1 is for terminal / recovery launches without the agent.
_under_agent=0
if [[ "\${XPC_SERVICE_NAME:-}" == "\${BUNDLE_ID}" || "\${GBU_DIRECT:-}" == "1" ]]; then
  _under_agent=1
fi

if [[ "\${_under_agent}" -eq 0 ]]; then
  # Finder / open / double-click path — never exec Python under Launch Services
  # (that leaves the status item at height 0 on recent macOS).
  if launchctl print "\${DOMAIN}/\${BUNDLE_ID}" >/dev/null 2>&1; then
    # Drop orphans from a previous broken \`open\` so the agent owns the instance.
    for pid in \$(pgrep -f "\${RUNTIME}" 2>/dev/null || true); do
      if ps -p "\$pid" -o args= 2>/dev/null | grep -q -- '-m gbu'; then
        kill "\$pid" 2>/dev/null || true
      fi
    done
    sleep 0.2
    if launchctl kickstart -k "\${DOMAIN}/\${BUNDLE_ID}" 2>/dev/null \\
      || launchctl kickstart "\${DOMAIN}/\${BUNDLE_ID}" 2>/dev/null; then
      exit 0
    fi
  fi
  # No LaunchAgent: start a one-shot launchd job so we are not LS-attributed.
  # (Terminal users without --login still get a visible menu-bar item.)
  launchctl remove "\${BUNDLE_ID}.oneshot" 2>/dev/null || true
  # shellcheck disable=SC2086
  if launchctl submit -l "\${BUNDLE_ID}.oneshot" \\
      -o "\${LOG_FILE}" -e "\${LOG_FILE}" \\
      -- /usr/bin/env \\
      "GBU_DIRECT=1" \\
      "PYTHONHOME=\${PYTHON_HOME}" \\
      "PYTHONPATH=\${PYTHONPATH}" \\
      "PYTHONUNBUFFERED=1" \\
      "VIRTUAL_ENV=\${PROJECT_DIR}/.venv" \\
      "\${RUNTIME}" -m gbu 2>/dev/null; then
    exit 0
  fi
  # Last resort: direct exec (works from Terminal; may fail under pure LS).
  export GBU_DIRECT=1
  exec env GBU_DIRECT=1 "\$0" "\$@"
fi

# Single-instance under the agent/direct path only.
# Exit 0 so LaunchAgent KeepAlive (SuccessfulExit=false) does not thrash.
_already=0
for pid in \$(pgrep -f "\${RUNTIME}" 2>/dev/null || true); do
  if ps -p "\$pid" -o args= 2>/dev/null | grep -q -- '-m gbu'; then
    _already=1
    break
  fi
done
if [[ "\${_already}" -eq 1 ]]; then
  osascript -e 'display notification "Already running — look for the chart icon + GBU · % in the menu bar" with title "Grok Build Usage"' 2>/dev/null || true
  exit 0
fi

export PYTHONHOME="\${PYTHON_HOME}"
export PYTHONPATH
export PYTHONUNBUFFERED=1
export VIRTUAL_ENV="\${PROJECT_DIR}/.venv"
cd "\${PROJECT_DIR}"

# Rotate log if it gets huge (status-watch spam from older builds).
if [[ -f "\${LOG_FILE}" ]]; then
  log_size="\$(wc -c <"\${LOG_FILE}" | tr -d ' ')"
  if [[ "\${log_size}" -gt 5000000 ]]; then
    mv "\${LOG_FILE}" "\${LOG_FILE}.1" 2>/dev/null || true
  fi
fi

exec >>"\${LOG_FILE}" 2>&1
echo "---- \$(date -u +%Y-%m-%dT%H:%M:%SZ) start ----"
echo "runtime=\${RUNTIME} (bundle-attributed process name) xpc=\${XPC_SERVICE_NAME:-} direct=\${GBU_DIRECT:-0}"
exec "\${RUNTIME}" -m gbu
EOF
chmod +x "${APP_DIR}/Contents/MacOS/gbu"

# Info.plist — LSUIElement = agent (menu bar only, no Dock icon)
# CFBundleName/DisplayName drive the "Allow in the Menu Bar" label once the
# running executable lives inside this bundle.
cat > "${APP_DIR}/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key>
  <string>en</string>
  <key>CFBundleDisplayName</key>
  <string>${APP_NAME}</string>
  <key>CFBundleExecutable</key>
  <string>gbu</string>
  <key>CFBundleIdentifier</key>
  <string>${BUNDLE_ID}</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundleName</key>
  <string>${APP_NAME}</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleShortVersionString</key>
  <string>0.1.0</string>
  <key>CFBundleVersion</key>
  <string>0.1.0</string>
  <key>LSMinimumSystemVersion</key>
  <string>12.0</string>
  <key>LSUIElement</key>
  <true/>
  <key>NSHighResolutionCapable</key>
  <true/>
  <key>NSPrincipalClass</key>
  <string>NSApplication</string>
</dict>
</plist>
EOF

echo "APPL????" > "${APP_DIR}/Contents/PkgInfo"

# Optional simple icon via SF Symbol → PNG → icns (best-effort)
ICONSET="${APP_DIR}/Contents/Resources/AppIcon.iconset"
if "${PYTHON_BIN}" - <<'PY' "${ICONSET}" 2>/dev/null
import sys
from pathlib import Path
from AppKit import (
    NSApplication,
    NSBitmapImageRep,
    NSColor,
    NSImage,
    NSImageSymbolConfiguration,
    NSFontWeightMedium,
    NSImageScaleProportionallyUpOrDown,
)

NSApplication.sharedApplication()
out = Path(sys.argv[1])
out.mkdir(parents=True, exist_ok=True)

def make_png(size: int, path: Path) -> None:
    img = NSImage.imageWithSystemSymbolName_accessibilityDescription_(
        "wrench.and.screwdriver", None
    )
    if img is None:
        return
    cfg = NSImageSymbolConfiguration.configurationWithPointSize_weight_scale_(
        size * 0.55, NSFontWeightMedium, 1
    )
    img = img.imageWithSymbolConfiguration_(cfg) or img
    canvas = NSImage.alloc().initWithSize_((size, size))
    canvas.lockFocus()
    NSColor.colorWithCalibratedRed_green_blue_alpha_(0.07, 0.07, 0.09, 1.0).set()
    from AppKit import NSBezierPath, NSMakeRect
    NSBezierPath.bezierPathWithRoundedRect_xRadius_yRadius_(
        NSMakeRect(0, 0, size, size), size * 0.22, size * 0.22
    ).fill()
    # zinc glyph
    tinted = img.copy()
    tinted.setTemplate_(True)
    margin = size * 0.18
    tinted.drawInRect_fromRect_operation_fraction_(
        NSMakeRect(margin, margin, size - 2 * margin, size - 2 * margin),
        NSMakeRect(0, 0, 0, 0),
        2,  # NSCompositingOperationSourceOver
        1.0,
    )
    canvas.unlockFocus()
    tiff = canvas.TIFFRepresentation()
    rep = NSBitmapImageRep.imageRepWithData_(tiff)
    png = rep.representationUsingType_properties_(4, None)  # NSPNGFileType
    path.write_bytes(bytes(png))

for s, name in [
    (16, "icon_16x16.png"),
    (32, "diana.k@example.org"),
    (32, "icon_32x32.png"),
    (64, "ivan.p@example.net"),
    (128, "icon_128x128.png"),
    (256, "wendy.h@example.net"),
    (256, "icon_256x256.png"),
    (512, "wendy.h@example.net"),
    (512, "icon_512x512.png"),
    (1024, "walt.e@example.net"),
]:
    make_png(s, out / name)
print("ok")
PY
then
  if command -v iconutil >/dev/null 2>&1; then
    iconutil -c icns "${ICONSET}" -o "${APP_DIR}/Contents/Resources/AppIcon.icns" 2>/dev/null || true
    rm -rf "${ICONSET}"
    if [[ -f "${APP_DIR}/Contents/Resources/AppIcon.icns" ]]; then
      /usr/libexec/PlistBuddy -c 'Add :CFBundleIconFile string AppIcon' \
        "${APP_DIR}/Contents/Info.plist" 2>/dev/null \
        || /usr/libexec/PlistBuddy -c 'Set :CFBundleIconFile AppIcon' \
        "${APP_DIR}/Contents/Info.plist" 2>/dev/null || true
    fi
  fi
fi

# Clear quarantine if present (downloaded / script-built apps)
xattr -dr com.apple.quarantine "${APP_DIR}" 2>/dev/null || true

# Refresh Launch Services registration
if [[ -x /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister ]]; then
  /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister \
    -f "${APP_DIR}" 2>/dev/null || true
fi

echo "==> Installed: ${APP_DIR}"
echo "    Menu Bar allow-list name on this Mac is usually **python3.11** (sticky)."
echo "    Keep that toggle ON so the GBU · % status item can appear."

# ── Optional LaunchAgent (start at login) ───────────────────────────────────
if [[ "${DO_LOGIN}" -eq 1 ]]; then
  mkdir -p "${LAUNCH_AGENT_DIR}" "${LOG_DIR}"
  # Drop legacy personal id if present so only the neutral agent remains
  launchctl bootout "gui/$(id -u)/com.vbusnita.grok-build-usage" 2>/dev/null || true
  rm -f "${HOME}/Library/LaunchAgents/com.vbusnita.grok-build-usage.plist"
  # Launch the in-bundle launcher directly (not `open -ga`). Launch Services
  # attribution to the .app bundle can put the NSStatusItem under a different
  # Control Center identity than the sticky "python3.11" allow-list row, so the
  # menu bar button never gets a frame. Direct exec matches that allow entry.
  cat > "${LAUNCH_AGENT_PLIST}" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${BUNDLE_ID}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${APP_DIR}/Contents/MacOS/gbu</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <!-- Restart only on crash / non-zero exit. Menu-bar Quit exits 0 → stay quit. -->
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>
  <key>ThrottleInterval</key>
  <integer>10</integer>
  <key>ProcessType</key>
  <string>Interactive</string>
  <key>StandardOutPath</key>
  <string>${LOG_FILE}</string>
  <key>StandardErrorPath</key>
  <string>${LOG_FILE}</string>
</dict>
</plist>
EOF
  launchctl bootout "gui/$(id -u)/${BUNDLE_ID}" 2>/dev/null || true
  launchctl bootstrap "gui/$(id -u)" "${LAUNCH_AGENT_PLIST}"
  launchctl enable "gui/$(id -u)/${BUNDLE_ID}" 2>/dev/null || true
  echo "==> Login item: LaunchAgent ${BUNDLE_ID}"
  echo "    Disable later: launchctl bootout gui/\$(id -u)/${BUNDLE_ID}"
fi

if [[ "${DO_OPEN}" -eq 1 ]]; then
  echo "==> Opening…"
  open "${APP_DIR}"
fi

echo ""
echo "Done. Open from Spotlight / Finder:"
echo "  open \"${APP_DIR}\""
echo ""
echo "Or double-click:  ~/Applications/${APP_NAME}.app"
echo "Logs:             ${LOG_FILE}"
if [[ "${DO_LOGIN}" -eq 0 ]]; then
  echo ""
  echo "Start at login next time:"
  echo "  ${PROJECT_DIR}/scripts/install-app.sh --login"
fi
