#!/usr/bin/env bash
# Install Grok Build Usage as a macOS menu-bar app (+ optional login item).
#
# Usage:
#   ./scripts/install-app.sh              # build ~/Applications/Grok Build Usage.app
#   ./scripts/install-app.sh --login      # also start at login (LaunchAgent)
#   ./scripts/install-app.sh --open       # launch after install
#   ./scripts/install-app.sh --login --open
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
APP_NAME="Grok Build Usage"
APP_DIR="${HOME}/Applications/${APP_NAME}.app"
# Neutral reverse-DNS id (not personal) — used for LaunchAgent + Info.plist
BUNDLE_ID="app.grokbuild.usage"
LAUNCH_AGENT_DIR="${HOME}/Library/LaunchAgents"
LAUNCH_AGENT_PLIST="${LAUNCH_AGENT_DIR}/${BUNDLE_ID}.plist"
LOG_DIR="${HOME}/Library/Logs"
LOG_FILE="${LOG_DIR}/grok-build-usage.log"

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "error: Grok Build Usage is macOS-only." >&2
  exit 1
fi

if [[ ! -f "${HOME}/.grok/auth.json" ]]; then
  echo "note: ~/.grok/auth.json not found yet."
  echo "      Install/open Grok Build and run:  grok login"
  echo "      (or /login inside the TUI). You can still install the app now."
  echo ""
fi

DO_LOGIN=0
DO_OPEN=0
for arg in "$@"; do
  case "$arg" in
    --login) DO_LOGIN=1 ;;
    --open)  DO_OPEN=1 ;;
    -h|--help)
      sed -n '2,12p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown flag: $arg" >&2
      exit 2
      ;;
  esac
done

echo "==> Project:  ${PROJECT_DIR}"
echo "==> App:      ${APP_DIR}"

# ── Ensure venv + package ───────────────────────────────────────────────────
if [[ ! -x "${PROJECT_DIR}/.venv/bin/python" ]]; then
  echo "==> Creating venv (python3.11 preferred)…"
  if command -v python3.11 >/dev/null 2>&1; then
    python3.11 -m venv "${PROJECT_DIR}/.venv"
  else
    python3 -m venv "${PROJECT_DIR}/.venv"
  fi
fi

# shellcheck disable=SC1091
source "${PROJECT_DIR}/.venv/bin/activate"
python -m pip install -q -U pip setuptools wheel
python -m pip install -q -e "${PROJECT_DIR}"
deactivate

PYTHON_BIN="${PROJECT_DIR}/.venv/bin/python"
if ! "${PYTHON_BIN}" -c "import gbu" 2>/dev/null; then
  echo "error: gbu package not importable from ${PYTHON_BIN}" >&2
  exit 1
fi

# Resolve real interpreter + stdlib home so we can embed a *named* Mach-O inside
# the .app. System Settings → Desktop & Dock → "Allow in the Menu Bar" labels
# entries by the running executable; exec'ing bare python3.11 shows "python3.11".
# A copy of the interpreter living at Contents/MacOS/GrokBuildUsage is attributed
# to this bundle and shows as "Grok Build Usage".
PY_META="$("${PYTHON_BIN}" - <<'PY'
import pathlib, sys
print(f"{sys.version_info.major}.{sys.version_info.minor}")
print(pathlib.Path(sys.executable).resolve())
print(sys.base_prefix)
PY
)"
PY_VERSION="$(printf '%s\n' "${PY_META}" | sed -n '1p')"
REAL_PYTHON="$(printf '%s\n' "${PY_META}" | sed -n '2p')"
PYTHON_HOME="$(printf '%s\n' "${PY_META}" | sed -n '3p')"
SITE_PACKAGES="${PROJECT_DIR}/.venv/lib/python${PY_VERSION}/site-packages"
SRC_PATH="${PROJECT_DIR}/src"
echo "==> Python ${PY_VERSION}  home=${PYTHON_HOME}"
echo "    real binary: ${REAL_PYTHON}"
if [[ ! -x "${REAL_PYTHON}" ]]; then
  echo "error: could not resolve real Python binary from venv" >&2
  exit 1
fi
if [[ ! -d "${PYTHON_HOME}" ]]; then
  echo "error: PYTHON home missing at ${PYTHON_HOME}" >&2
  exit 1
fi
if [[ ! -d "${SITE_PACKAGES}" ]]; then
  echo "error: site-packages missing at ${SITE_PACKAGES}" >&2
  exit 1
fi

# ── Build .app bundle ───────────────────────────────────────────────────────
echo "==> Building app bundle…"
rm -rf "${APP_DIR}"
mkdir -p "${APP_DIR}/Contents/MacOS" "${APP_DIR}/Contents/Resources"

# Embed a copy of the interpreter under a bundle-local name (not a symlink —
# macOS resolves symlink targets). Keep the *original* linker-signed CDHash:
# System Settings → Menu Bar → "Allow in the Menu Bar" already has a sticky
# row named "python3.11" for that code identity. Ad-hoc re-signing breaks the
# match (new CDHash) and the new identity never gets its own Settings row, so
# the status item stays permanently height-0. Correct long-term naming needs a
# non-Python host binary + a clean Control Center registration — not re-sign.
echo "==> Embedding interpreter as Contents/MacOS/GrokBuildUsage…"
cp "${REAL_PYTHON}" "${APP_DIR}/Contents/MacOS/GrokBuildUsage"
chmod +x "${APP_DIR}/Contents/MacOS/GrokBuildUsage"

# Launcher name is the human app name so Background Items / notifications say
# "Grok Build Usage", not "gbu". Embedded Python stays GrokBuildUsage (menu-bar
# allow-list CDHash). Launch Services entry point re-dispatches via LaunchAgent.
LAUNCHER_NAME="GrokBuildUsageApp"
cat > "${APP_DIR}/Contents/MacOS/${LAUNCHER_NAME}" <<EOF
#!/usr/bin/env bash
# Grok Build Usage — menu bar launcher (generated by install-app.sh)
#
# Launch paths matter on recent macOS:
#   - LaunchAgent / direct exec → status item gets a real menu-bar frame
#   - Finder / \`open\` / Spotlight (Launch Services) → often height-0 forever
#     (Control Center allow-list identity differs)
# So when this script is NOT already running as our LaunchAgent job, re-dispatch
# via launchctl kickstart instead of exec'ing Python under Launch Services.
#
# Soft relaunch: if already running, exit quietly. Do NOT kill/kickstart -k on
# every open — that re-triggers macOS "App Background Activity" notifications.
set -euo pipefail

DIR="\$(cd "\$(dirname "\$0")" && pwd)"
PROJECT_DIR="${PROJECT_DIR}"
RUNTIME="\${DIR}/GrokBuildUsage"
PYTHON_HOME="${PYTHON_HOME}"
PYTHONPATH="${SRC_PATH}:${SITE_PACKAGES}"
LOG_DIR="${LOG_DIR}"
LOG_FILE="${LOG_FILE}"
BUNDLE_ID="${BUNDLE_ID}"
DOMAIN="gui/\$(id -u)"
mkdir -p "\${LOG_DIR}"

_runtime_running() {
  for pid in \$(pgrep -x GrokBuildUsage 2>/dev/null || true); do
    if ps -p "\$pid" -o args= 2>/dev/null | grep -q -- '-m gbu'; then
      return 0
    fi
  done
  return 1
}

if [[ ! -x "\${RUNTIME}" ]]; then
  osascript -e 'display notification "GrokBuildUsage runtime missing — re-run install-app.sh" with title "Grok Build Usage"' 2>/dev/null || true
  echo "missing runtime: \${RUNTIME}" >>"\${LOG_FILE}"
  exit 1
fi

# Real process start: LaunchAgent sets XPC_SERVICE_NAME to our label.
# GBU_DIRECT=1 is for terminal / recovery launches without the agent.
_under_agent=0
if [[ "\${XPC_SERVICE_NAME:-}" == "\${BUNDLE_ID}" || "\${GBU_DIRECT:-}" == "1" ]]; then
  _under_agent=1
fi

if [[ "\${_under_agent}" -eq 0 ]]; then
  # Finder / open / double-click — re-dispatch; never exec Python under LS.
  if _runtime_running; then
    # Already up (agent-owned). Silent no-op — no Dock, no extra notifications.
    exit 0
  fi
  if launchctl print "\${DOMAIN}/\${BUNDLE_ID}" >/dev/null 2>&1; then
    # Start only if stopped. No -k (force restart) — avoids BTM re-notify spam.
    if launchctl kickstart "\${DOMAIN}/\${BUNDLE_ID}" 2>/dev/null; then
      exit 0
    fi
  fi
  # No LaunchAgent: direct path (Terminal). May fail under pure Launch Services.
  export GBU_DIRECT=1
  exec env GBU_DIRECT=1 "\$0" "\$@"
fi

# Single-instance under the agent/direct path only.
# Exit 0 so LaunchAgent KeepAlive (SuccessfulExit=false) does not thrash.
if _runtime_running; then
  exit 0
fi

export PYTHONHOME="\${PYTHON_HOME}"
export PYTHONPATH
export PYTHONUNBUFFERED=1
export VIRTUAL_ENV="\${PROJECT_DIR}/.venv"
cd "\${PROJECT_DIR}"

# Rotate log if it gets huge (status-watch spam from older builds).
if [[ -f "\${LOG_FILE}" ]]; then
  log_size="\$(wc -c <"\${LOG_FILE}" | tr -d ' ')"
  if [[ "\${log_size}" -gt 5000000 ]]; then
    mv "\${LOG_FILE}" "\${LOG_FILE}.1" 2>/dev/null || true
  fi
fi

exec >>"\${LOG_FILE}" 2>&1
echo "---- \$(date -u +%Y-%m-%dT%H:%M:%SZ) start ----"
echo "runtime=\${RUNTIME} (bundle-attributed process name) xpc=\${XPC_SERVICE_NAME:-} direct=\${GBU_DIRECT:-0}"
exec "\${RUNTIME}" -m gbu
EOF
chmod +x "${APP_DIR}/Contents/MacOS/${LAUNCHER_NAME}"
# Compat symlink for older LaunchAgent plists / docs that still point at gbu
ln -sfn "${LAUNCHER_NAME}" "${APP_DIR}/Contents/MacOS/gbu"

# Info.plist — LSUIElement = agent (menu bar only, no Dock icon)
# CFBundleName/DisplayName drive Settings labels; executable name is what the
# "App Background Activity" banner quotes.
cat > "${APP_DIR}/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key>
  <string>en</string>
  <key>CFBundleDisplayName</key>
  <string>${APP_NAME}</string>
  <key>CFBundleExecutable</key>
  <string>${LAUNCHER_NAME}</string>
  <key>CFBundleIdentifier</key>
  <string>${BUNDLE_ID}</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundleName</key>
  <string>${APP_NAME}</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleShortVersionString</key>
  <string>0.1.0</string>
  <key>CFBundleVersion</key>
  <string>0.1.0</string>
  <key>LSMinimumSystemVersion</key>
  <string>12.0</string>
  <key>LSUIElement</key>
  <true/>
  <key>NSHighResolutionCapable</key>
  <true/>
  <key>NSPrincipalClass</key>
  <string>NSApplication</string>
</dict>
</plist>
EOF

echo "APPL????" > "${APP_DIR}/Contents/PkgInfo"

# App icon + menu-bar template from packaged assets (usage-bars mark)
ASSETS_DIR="${PROJECT_DIR}/src/gbu/assets"
RESOURCES_DIR="${APP_DIR}/Contents/Resources"
mkdir -p "${RESOURCES_DIR}"

# Copy monochrome menu-bar templates into the bundle (template = system-tinted)
for f in MenuBarTemplate.png "MenuBarTemplate@2x.png"; do
  if [[ -f "${ASSETS_DIR}/${f}" ]]; then
    cp -f "${ASSETS_DIR}/${f}" "${RESOURCES_DIR}/${f}"
  fi
done

ICONSET="${RESOURCES_DIR}/AppIcon.iconset"
APPICON_MASTER="${ASSETS_DIR}/AppIcon.png"
if [[ -f "${APPICON_MASTER}" ]] && command -v iconutil >/dev/null 2>&1 && command -v sips >/dev/null 2>&1; then
  echo "==> Building AppIcon.icns from assets/AppIcon.png"
  rm -rf "${ICONSET}"
  mkdir -p "${ICONSET}"
  # Full-bleed master → every iconset size (Finder / Spotlight / Get Info).
  # sips is system-provided (no Pillow). Write via a temp *.png path first —
  # sips mishandles @2x filenames when used as --out directly.
  while IFS=' ' read -r size name; do
    tmp="$(mktemp -t gbu-icon).png"
    sips -z "${size}" "${size}" "${APPICON_MASTER}" --out "${tmp}" >/dev/null
    mv -f "${tmp}" "${ICONSET}/${name}"
  done <<'SIZES'
16 icon_16x16.png
32 diana.k@example.org
32 icon_32x32.png
64 ivan.p@example.net
128 icon_128x128.png
256 wendy.h@example.net
256 icon_256x256.png
512 wendy.h@example.net
512 icon_512x512.png
1024 walt.e@example.net
SIZES
  if iconutil -c icns "${ICONSET}" -o "${RESOURCES_DIR}/AppIcon.icns"; then
    rm -rf "${ICONSET}"
    /usr/libexec/PlistBuddy -c 'Add :CFBundleIconFile string AppIcon' \
      "${APP_DIR}/Contents/Info.plist" 2>/dev/null \
      || /usr/libexec/PlistBuddy -c 'Set :CFBundleIconFile AppIcon' \
      "${APP_DIR}/Contents/Info.plist" 2>/dev/null || true
    cp -f "${APPICON_MASTER}" "${RESOURCES_DIR}/AppIcon.png"
  else
    echo "warning: iconutil failed — AppIcon.icns not built" >&2
    rm -rf "${ICONSET}"
  fi
else
  echo "warning: assets/AppIcon.png, sips, or iconutil missing — no custom Finder icon" >&2
fi

# Clear quarantine if present (downloaded / script-built apps)
xattr -dr com.apple.quarantine "${APP_DIR}" 2>/dev/null || true

# Refresh Launch Services registration
if [[ -x /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister ]]; then
  /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister \
    -f "${APP_DIR}" 2>/dev/null || true
fi

echo "==> Installed: ${APP_DIR}"
echo "    Menu Bar allow-list name on this Mac is usually **python3.11** (sticky)."
echo "    Keep that toggle ON so the GBU · % status item can appear."

# ── Optional LaunchAgent (start at login) ───────────────────────────────────
if [[ "${DO_LOGIN}" -eq 1 ]]; then
  mkdir -p "${LAUNCH_AGENT_DIR}" "${LOG_DIR}"
  # Drop legacy personal id if present so only the neutral agent remains
  launchctl bootout "gui/$(id -u)/com.vbusnita.grok-build-usage" 2>/dev/null || true
  rm -f "${HOME}/Library/LaunchAgents/com.vbusnita.grok-build-usage.plist"
  # Launch the in-bundle launcher directly (not `open -ga`). Launch Services
  # attribution to the .app bundle can put the NSStatusItem under a different
  # Control Center identity than the sticky "python3.11" allow-list row, so the
  # menu bar button never gets a frame. Direct exec matches that allow entry.
  cat > "${LAUNCH_AGENT_PLIST}" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${BUNDLE_ID}</string>
  <key>AssociatedBundleIdentifiers</key>
  <array>
    <string>${BUNDLE_ID}</string>
  </array>
  <key>ProgramArguments</key>
  <array>
    <string>${APP_DIR}/Contents/MacOS/${LAUNCHER_NAME}</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <!-- Restart only on crash / non-zero exit. Menu-bar Quit exits 0 → stay quit. -->
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>
  <key>ThrottleInterval</key>
  <integer>10</integer>
  <key>ProcessType</key>
  <string>Interactive</string>
  <key>StandardOutPath</key>
  <string>${LOG_FILE}</string>
  <key>StandardErrorPath</key>
  <string>${LOG_FILE}</string>
</dict>
</plist>
EOF
  launchctl bootout "gui/$(id -u)/${BUNDLE_ID}" 2>/dev/null || true
  launchctl bootstrap "gui/$(id -u)" "${LAUNCH_AGENT_PLIST}"
  launchctl enable "gui/$(id -u)/${BUNDLE_ID}" 2>/dev/null || true
  echo "==> Login item: LaunchAgent ${BUNDLE_ID}"
  echo "    In System Settings → General → Login Items & Extensions, leave"
  echo "    **Grok Build Usage** allowed (one-time approve is enough)."
  echo "    Disable later: launchctl bootout gui/\$(id -u)/${BUNDLE_ID}"
fi

if [[ "${DO_OPEN}" -eq 1 ]]; then
  echo "==> Opening…"
  open "${APP_DIR}"
fi

echo ""
echo "Done. Open from Spotlight / Finder:"
echo "  open \"${APP_DIR}\""
echo ""
echo "Or double-click:  ~/Applications/${APP_NAME}.app"
echo "Logs:             ${LOG_FILE}"
if [[ "${DO_LOGIN}" -eq 0 ]]; then
  echo ""
  echo "Start at login next time:"
  echo "  ${PROJECT_DIR}/scripts/install-app.sh --login"
fi
